DROP TABLE IF EXISTS ${DESTINATION_DB}.TEST_SIMSMART_VW_DWEP_PO_AND_SE_LINE_ITEM;
CREATE TABLE ${DESTINATION_DB}.TEST_SIMSMART_VW_DWEP_PO_AND_SE_LINE_ITEM
STORED AS parquet
LOCATION "${LOCATION_PATH}/TEST_SIMSMART_VW_DWEP_PO_AND_SE_LINE_ITEM"
AS
SELECT * FROM ${SOURCE_DB}.SIMSMART_VW_DWEP_PO_AND_SE_LINE_ITEM T
WHERE spend_type_name in ("Non-Catalog", "Zero-Priced Catalog") and start_date >= 20150000 and quantity_llf > 0;

ALTER TABLE ${DESTINATION_DB}.TEST_SIMSMART_VW_DWEP_PO_AND_SE_LINE_ITEM SET TBLPROPERTIES('EXTERNAL'='TRUE');