DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_metadata_info;
DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_invoice;
DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_interval_problem;
DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_invoice_to_npt_link;
DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_invoice_for_full_sf;
DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_interval_problem_full_sf;
DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_afe_detail;
DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_interval_problem_full_with_link_sf;
DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_time_log_detail;
DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_invoice_detail;
DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_overcharge_group;
DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_overcharge_detail;
DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_pdf_contract_info;
DROP TABLE IF EXISTS  ${DESTINATION_DB}.test_amendments_to_contracts;

CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_metadata_info (id int) LOCATION "${OUTPUT_PATH}/test_metadata_info";
CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_invoice (id int) LOCATION "${OUTPUT_PATH}/test_invoice";
CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_interval_problem (id int) LOCATION "${OUTPUT_PATH}/test_interval_problem";
CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_invoice_to_npt_link (id int) LOCATION "${OUTPUT_PATH}/test_invoice_to_npt_link";
CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_invoice_for_full_sf (id int) LOCATION "${OUTPUT_PATH}/test_invoice_for_full_sf";
CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_interval_problem_full_sf (id int) LOCATION "${OUTPUT_PATH}/test_interval_problem_full_sf";
CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_afe_detail (id int) LOCATION "${OUTPUT_PATH}/test_afe_detail";
CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_interval_problem_full_with_link_sf (id int) LOCATION "${OUTPUT_PATH}/test_interval_problem_full_with_link_sf";
CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_time_log_detail (id int) LOCATION "${OUTPUT_PATH}/test_time_log_detail";
CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_invoice_detail (id int) LOCATION "${OUTPUT_PATH}/test_invoice_detail";
CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_overcharge_group (id int) LOCATION "${OUTPUT_PATH}/test_overcharge_group";
CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_overcharge_detail (id int) LOCATION "${OUTPUT_PATH}/test_overcharge_detail";
CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_pdf_contract_info (id int) LOCATION "${OUTPUT_PATH}/test_pdf_contract_info";
CREATE EXTERNAL TABLE IF NOT EXISTS ${DESTINATION_DB}.test_amendments_to_contracts (id int) LOCATION "${OUTPUT_PATH}/test_amendments_to_contracts";