DROP TABLE IF EXISTS ${DESTINATION_DB}.WVCASCOMP;
CREATE TABLE ${DESTINATION_DB}.WVCASCOMP
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVCASCOMP"
AS
SELECT * FROM ${SOURCE_DB}.WVCASCOMP T;

ALTER TABLE ${DESTINATION_DB}.WVCASCOMP SET TBLPROPERTIES('EXTERNAL'='TRUE');
