DROP TABLE IF EXISTS ${DESTINATION_DB}.WVCAS;
CREATE TABLE ${DESTINATION_DB}.WVCAS
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVCAS"
AS
SELECT * FROM ${SOURCE_DB}.WVCAS T;

ALTER TABLE ${DESTINATION_DB}.WVCAS SET TBLPROPERTIES('EXTERNAL'='TRUE');
