DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBSAFETYINCIDENTVICT;
CREATE TABLE ${DESTINATION_DB}.WVJOBSAFETYINCIDENTVICT
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBSAFETYINCIDENTVICT"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBSAFETYINCIDENTVICT T;

ALTER TABLE ${DESTINATION_DB}.WVJOBSAFETYINCIDENTVICT SET TBLPROPERTIES('EXTERNAL'='TRUE');
