DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBREPORTOFFSHORE;
CREATE TABLE ${DESTINATION_DB}.WVJOBREPORTOFFSHORE
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBREPORTOFFSHORE"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBREPORTOFFSHORE T;

ALTER TABLE ${DESTINATION_DB}.WVJOBREPORTOFFSHORE SET TBLPROPERTIES('EXTERNAL'='TRUE');
