DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBAFE;
CREATE TABLE ${DESTINATION_DB}.WVJOBAFE
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBAFE"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBAFE T;

ALTER TABLE ${DESTINATION_DB}.WVJOBAFE SET TBLPROPERTIES('EXTERNAL'='TRUE');
