DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBOFFLINE;
CREATE TABLE ${DESTINATION_DB}.WVJOBOFFLINE
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBOFFLINE"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBOFFLINE T;

ALTER TABLE ${DESTINATION_DB}.WVJOBOFFLINE SET TBLPROPERTIES('EXTERNAL'='TRUE');
