DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBSAFETYCHK;
CREATE TABLE ${DESTINATION_DB}.WVJOBSAFETYCHK
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBSAFETYCHK"
AS
SELECT idrec, idrecparent, des, typ, inspector, result, com,
to_date(from_unixtime(cast(to_utc_timestamp(dttm,'CST') as bigint))) as dttmdate


FROM ${SOURCE_DB}.WVJOBSAFETYCHK T;

ALTER TABLE ${DESTINATION_DB}.WVJOBSAFETYCHK SET TBLPROPERTIES('EXTERNAL'='TRUE');
