DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBREPORTHAZARDID;
CREATE TABLE ${DESTINATION_DB}.WVJOBREPORTHAZARDID
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBREPORTHAZARDID"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBREPORTHAZARDID T;

ALTER TABLE ${DESTINATION_DB}.WVJOBREPORTHAZARDID SET TBLPROPERTIES('EXTERNAL'='TRUE');
