DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBREPORTCONTACTS;
CREATE TABLE ${DESTINATION_DB}.WVJOBREPORTCONTACTS
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBREPORTCONTACTS"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBREPORTCONTACTS T;

ALTER TABLE ${DESTINATION_DB}.WVJOBREPORTCONTACTS SET TBLPROPERTIES('EXTERNAL'='TRUE');
