DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBRIGBOPCOMP;
CREATE TABLE ${DESTINATION_DB}.WVJOBRIGBOPCOMP
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBRIGBOPCOMP"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBRIGBOPCOMP T;

ALTER TABLE ${DESTINATION_DB}.WVJOBRIGBOPCOMP SET TBLPROPERTIES('EXTERNAL'='TRUE');
