DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBREPORTFLUIDSWELL;
CREATE TABLE ${DESTINATION_DB}.WVJOBREPORTFLUIDSWELL
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBREPORTFLUIDSWELL"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBREPORTFLUIDSWELL T;

ALTER TABLE ${DESTINATION_DB}.WVJOBREPORTFLUIDSWELL SET TBLPROPERTIES('EXTERNAL'='TRUE');
