DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBDRILLSTRINGDRILLPARAM;
CREATE TABLE ${DESTINATION_DB}.WVJOBDRILLSTRINGDRILLPARAM
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBDRILLSTRINGDRILLPARAM"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBDRILLSTRINGDRILLPARAM T;

ALTER TABLE ${DESTINATION_DB}.WVJOBDRILLSTRINGDRILLPARAM SET TBLPROPERTIES('EXTERNAL'='TRUE');
