DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBKICK;
CREATE TABLE ${DESTINATION_DB}.WVJOBKICK
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBKICK"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBKICK T;

ALTER TABLE ${DESTINATION_DB}.WVJOBKICK SET TBLPROPERTIES('EXTERNAL'='TRUE');
