DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBCONTACT;
CREATE TABLE ${DESTINATION_DB}.WVJOBCONTACT
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBCONTACT"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBCONTACT T;

ALTER TABLE ${DESTINATION_DB}.WVJOBCONTACT SET TBLPROPERTIES('EXTERNAL'='TRUE');
