DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBSAFETYINCIDENT;
CREATE TABLE ${DESTINATION_DB}.WVJOBSAFETYINCIDENT
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBSAFETYINCIDENT"
AS
SELECT t.*
FROM ${SOURCE_DB}.WVJOBSAFETYINCIDENT T;

ALTER TABLE ${DESTINATION_DB}.WVJOBSAFETYINCIDENT SET TBLPROPERTIES('EXTERNAL'='TRUE');
