DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBDRILLSTRINGCOMP;
CREATE TABLE ${DESTINATION_DB}.WVJOBDRILLSTRINGCOMP
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBDRILLSTRINGCOMP"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBDRILLSTRINGCOMP T;

ALTER TABLE ${DESTINATION_DB}.WVJOBDRILLSTRINGCOMP SET TBLPROPERTIES('EXTERNAL'='TRUE');
