DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBREPORTMUDCHK;
CREATE TABLE ${DESTINATION_DB}.WVJOBREPORTMUDCHK
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBREPORTMUDCHK"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBREPORTMUDCHK T;

ALTER TABLE ${DESTINATION_DB}.WVJOBREPORTMUDCHK SET TBLPROPERTIES('EXTERNAL'='TRUE');
