DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOB;
CREATE TABLE ${DESTINATION_DB}.WVJOB
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOB"
AS
SELECT idrec, idwell, wvtyp, jobtyp, dttmstart, dttmend FROM ${SOURCE_DB}.WVJOB T;

ALTER TABLE ${DESTINATION_DB}.WVJOB SET TBLPROPERTIES('EXTERNAL'='TRUE');
