DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBOFFLINEDATESTIMELOG;
CREATE TABLE ${DESTINATION_DB}.WVJOBOFFLINEDATESTIMELOG
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVJOBOFFLINEDATESTIMELOG"
AS
SELECT * FROM ${SOURCE_DB}.WVJOBOFFLINEDATESTIMELOG T;

ALTER TABLE ${DESTINATION_DB}.WVJOBOFFLINEDATESTIMELOG SET TBLPROPERTIES('EXTERNAL'='TRUE');
