DROP TABLE IF EXISTS ${DESTINATION_DB}.WVTESTEQUIP;
CREATE TABLE ${DESTINATION_DB}.WVTESTEQUIP
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVTESTEQUIP"
AS
SELECT * FROM ${SOURCE_DB}.WVTESTEQUIP T;

ALTER TABLE ${DESTINATION_DB}.WVTESTEQUIP SET TBLPROPERTIES('EXTERNAL'='TRUE');
