DROP TABLE IF EXISTS ${DESTINATION_DB}.WVTESTLEAKOFF;
CREATE TABLE ${DESTINATION_DB}.WVTESTLEAKOFF
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVTESTLEAKOFF"
AS
SELECT * FROM ${SOURCE_DB}.WVTESTLEAKOFF T;

ALTER TABLE ${DESTINATION_DB}.WVTESTLEAKOFF SET TBLPROPERTIES('EXTERNAL'='TRUE');
