DROP TABLE IF EXISTS ${DESTINATION_DB}.WVWELLHEADER;
CREATE TABLE ${DESTINATION_DB}.WVWELLHEADER
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVWELLHEADER"
AS
SELECT * FROM ${SOURCE_DB}.WVWELLHEADER T;

ALTER TABLE ${DESTINATION_DB}.WVWELLHEADER SET TBLPROPERTIES('EXTERNAL'='TRUE');
