DROP TABLE IF EXISTS ${DESTINATION_DB}.WVWELLBORE;
CREATE TABLE ${DESTINATION_DB}.WVWELLBORE
STORED AS parquet
LOCATION "${LOCATION_PATH}/WVWELLBORE"
AS
SELECT idrec, idrecparent, des, profiletyp, wellboreida, wellboreidb FROM ${SOURCE_DB}.WVWELLBORE T;

ALTER TABLE ${DESTINATION_DB}.WVWELLBORE SET TBLPROPERTIES('EXTERNAL'='TRUE');
