DROP TABLE IF EXISTS ${DESTINATION_DB}.WVCAS;
CREATE TABLE ${DESTINATION_DB}.WVCAS
STORED AS parquet LOCATION "${LOCATION_PATH}/WVCAS"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVCAS j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVCAS SET TBLPROPERTIES('EXTERNAL'='TRUE');
