DROP TABLE IF EXISTS ${DESTINATION_DB}.WVCASCOMP;

CREATE TABLE ${DESTINATION_DB}.WVCASCOMP
STORED AS parquet LOCATION "${LOCATION_PATH}/WVCASCOMP"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVCASCOMP j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVCASCOMP SET TBLPROPERTIES('EXTERNAL'='TRUE');
