DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBREPORTOFFSHORE;

CREATE TABLE ${DESTINATION_DB}.WVJOBREPORTOFFSHORE
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBREPORTOFFSHORE"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBREPORTOFFSHORE j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBREPORTOFFSHORE SET TBLPROPERTIES('EXTERNAL'='TRUE');
