DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBINTERVALPROBLEM;

CREATE TABLE ${DESTINATION_DB}.WVJOBINTERVALPROBLEM
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBINTERVALPROBLEM"
AS
SELECT
    jip.*
FROM ${SOURCE_DB}.WVJOBINTERVALPROBLEM jip
WHERE jip.idrecparent IN (SELECT j.idrec FROM ${DESTINATION_DB}.WVJOB j)
;
ALTER TABLE ${DESTINATION_DB}.WVJOBINTERVALPROBLEM SET TBLPROPERTIES('EXTERNAL'='TRUE');