DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBSAFETYCHK;

CREATE TABLE ${DESTINATION_DB}.WVJOBSAFETYCHK
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBSAFETYCHK"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBSAFETYCHK j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBSAFETYCHK SET TBLPROPERTIES('EXTERNAL'='TRUE');
