DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBOFFLINE;

CREATE TABLE ${DESTINATION_DB}.WVJOBOFFLINE
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBOFFLINE"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBOFFLINE j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBOFFLINE SET TBLPROPERTIES('EXTERNAL'='TRUE');
