DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBREPORTHAZARDID;

CREATE TABLE ${DESTINATION_DB}.WVJOBREPORTHAZARDID
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBREPORTHAZARDID"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBREPORTHAZARDID j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBREPORTHAZARDID SET TBLPROPERTIES('EXTERNAL'='TRUE');
