DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBSAFETYINCIDENT;

CREATE TABLE ${DESTINATION_DB}.WVJOBSAFETYINCIDENT
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBSAFETYINCIDENT"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBSAFETYINCIDENT j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBSAFETYINCIDENT SET TBLPROPERTIES('EXTERNAL'='TRUE');
