DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBLOSTCIRC;

CREATE TABLE ${DESTINATION_DB}.WVJOBLOSTCIRC
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBLOSTCIRC"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBLOSTCIRC j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBLOSTCIRC SET TBLPROPERTIES('EXTERNAL'='TRUE');
