DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBDRILLSTRINGDRILLPARAM;

CREATE TABLE ${DESTINATION_DB}.WVJOBDRILLSTRINGDRILLPARAM
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBDRILLSTRINGDRILLPARAM"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBDRILLSTRINGDRILLPARAM j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBDRILLSTRINGDRILLPARAM SET TBLPROPERTIES('EXTERNAL'='TRUE');
