DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBDRILLSTRINGCOMP;

CREATE TABLE ${DESTINATION_DB}.WVJOBDRILLSTRINGCOMP
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBDRILLSTRINGCOMP"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBDRILLSTRINGCOMP j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBDRILLSTRINGCOMP SET TBLPROPERTIES('EXTERNAL'='TRUE');
