DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBREPORTMUDVOL;

CREATE TABLE ${DESTINATION_DB}.WVJOBREPORTMUDVOL
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBREPORTMUDVOL"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBREPORTMUDVOL j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBREPORTMUDVOL SET TBLPROPERTIES('EXTERNAL'='TRUE');
