DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBREPORTCOSTGEN;

CREATE TABLE ${DESTINATION_DB}.WVJOBREPORTCOSTGEN
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBREPORTCOSTGEN"
AS
SELECT
    jrcg.*
FROM ${SOURCE_DB}.WVJOBREPORTCOSTGEN jrcg
WHERE jrcg.idrecparent IN (SELECT jr.idrec FROM ${DESTINATION_DB}.WVJOBREPORT jr)
;
ALTER TABLE  ${DESTINATION_DB}.WVJOBREPORTCOSTGEN SET TBLPROPERTIES('EXTERNAL'='TRUE');