DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBSERVICECONTRACT;

CREATE TABLE ${DESTINATION_DB}.WVJOBSERVICECONTRACT
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBSERVICECONTRACT"
AS
SELECT
    jr.*
FROM ${SOURCE_DB}.WVJOBSERVICECONTRACT jr
WHERE jr.idrecparent IN (SELECT j.idrec FROM ${DESTINATION_DB}.WVJOB j);

ALTER TABLE ${DESTINATION_DB}.WVJOBSERVICECONTRACT SET TBLPROPERTIES('EXTERNAL'='TRUE');