DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBREPORTFLUIDSWELL;

CREATE TABLE ${DESTINATION_DB}.WVJOBREPORTFLUIDSWELL
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBREPORTFLUIDSWELL"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBREPORTFLUIDSWELL j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBREPORTFLUIDSWELL SET TBLPROPERTIES('EXTERNAL'='TRUE');
