DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBRIGBOPCOMP;

CREATE TABLE ${DESTINATION_DB}.WVJOBRIGBOPCOMP
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBRIGBOPCOMP"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBRIGBOPCOMP j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBRIGBOPCOMP SET TBLPROPERTIES('EXTERNAL'='TRUE');
