DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBRIG;

CREATE TABLE ${DESTINATION_DB}.WVJOBRIG
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBRIG"
AS
SELECT
    jr.*
FROM ${SOURCE_DB}.WVJOBRIG jr
WHERE jr.idrecparent IN (SELECT j.idrec FROM ${DESTINATION_DB}.WVJOB j)
;
ALTER TABLE ${DESTINATION_DB}.WVJOBRIG SET TBLPROPERTIES('EXTERNAL'='TRUE');