DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBREPORTMUDCHK;

CREATE TABLE ${DESTINATION_DB}.WVJOBREPORTMUDCHK
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBREPORTMUDCHK"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBREPORTMUDCHK j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBREPORTMUDCHK SET TBLPROPERTIES('EXTERNAL'='TRUE');
