DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBPROGRAMPHASE;

CREATE TABLE ${DESTINATION_DB}.WVJOBPROGRAMPHASE
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBPROGRAMPHASE"
AS
SELECT
    jr.*
FROM ${SOURCE_DB}.WVJOBPROGRAMPHASE jr
WHERE jr.idrecparent IN (SELECT j.idrec FROM ${DESTINATION_DB}.WVJOB j);

ALTER TABLE ${DESTINATION_DB}.WVJOBPROGRAMPHASE SET TBLPROPERTIES('EXTERNAL'='TRUE');