DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBDRILLBIT;

CREATE TABLE ${DESTINATION_DB}.WVJOBDRILLBIT
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBDRILLBIT"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBDRILLBIT j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBDRILLBIT SET TBLPROPERTIES('EXTERNAL'='TRUE');
