DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBSAFETYINCIDENTVICT;

CREATE TABLE ${DESTINATION_DB}.WVJOBSAFETYINCIDENTVICT
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBSAFETYINCIDENTVICT"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBSAFETYINCIDENTVICT j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBSAFETYINCIDENTVICT SET TBLPROPERTIES('EXTERNAL'='TRUE');
