DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBKICK;

CREATE TABLE ${DESTINATION_DB}.WVJOBKICK
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBKICK"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBKICK j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBKICK SET TBLPROPERTIES('EXTERNAL'='TRUE');
