DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBREPORTTIMELOG;

CREATE TABLE ${DESTINATION_DB}.WVJOBREPORTTIMELOG
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBREPORTTIMELOG"
AS
SELECT
    jrtl.*
FROM ${SOURCE_DB}.WVJOBREPORTTIMELOG jrtl
WHERE jrtl.idrecparent IN (SELECT jr.idrec FROM ${DESTINATION_DB}.wvjobreport jr)
;

alter table ${DESTINATION_DB}.WVJOBREPORTTIMELOG SET TBLPROPERTIES('EXTERNAL'='TRUE');