DROP TABLE IF EXISTS ${DESTINATION_DB}.WVJOBREPORTCONTACTS;

CREATE TABLE ${DESTINATION_DB}.WVJOBREPORTCONTACTS
STORED AS parquet LOCATION "${LOCATION_PATH}/WVJOBREPORTCONTACTS"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVJOBREPORTCONTACTS j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVJOBREPORTCONTACTS SET TBLPROPERTIES('EXTERNAL'='TRUE');
