DROP TABLE IF EXISTS ${DESTINATION_DB}.WVTESTEQUIP;

CREATE TABLE ${DESTINATION_DB}.WVTESTEQUIP
STORED AS parquet LOCATION "${LOCATION_PATH}/WVTESTEQUIP"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVTESTEQUIP j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVTESTEQUIP SET TBLPROPERTIES('EXTERNAL'='TRUE');
