DROP TABLE IF EXISTS ${DESTINATION_DB}.WVWELLBORE;

CREATE TABLE ${DESTINATION_DB}.WVWELLBORE
STORED AS parquet LOCATION "${LOCATION_PATH}/WVWELLBORE"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVWELLBORE j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVWELLBORE SET TBLPROPERTIES('EXTERNAL'='TRUE');
