DROP TABLE IF EXISTS ${DESTINATION_DB}.WVWELLBOREFORMATION;

CREATE TABLE ${DESTINATION_DB}.WVWELLBOREFORMATION
STORED AS parquet LOCATION "${LOCATION_PATH}/WVWELLBOREFORMATION"
AS
SELECT
    j.*
FROM ${SOURCE_DB}.WVWELLBOREFORMATION j
WHERE TRIM(UPPER(j.idwell)) IN (SELECT TRIM(UPPER(h.idwell)) FROM ${DESTINATION_DB}.WVWELLHEADER h);


ALTER TABLE ${DESTINATION_DB}.WVWELLBOREFORMATION SET TBLPROPERTIES('EXTERNAL'='TRUE');
