export const INVOICES_VISIBLE_COLUMNS: string[] = [
  //1st column for checkbox
  'select',
  'parent_vendor',
  'contract_id',
  'contract_title',
  'contract_owner_name',
  'wbs_element',
  'npt_date_start',
  'npt_date_end',
  'npt_duration',
  'pt_spent_leakage_npt',
  // 'spent_leakage_confirmed',
  'ariba_doc_id',
  'price',
  'recovered',
  'status',
  'comment',
  'modified_by',
  'modified_date',
  'key',
  'work_start_date',
  'work_end_date',
  'by_date',
  'npt_ref_no',
  'is_weather',
  'jobtyp',
  'submit_date'
];
export const INVOICES_VISIBLE_COLUMNS_OBJECT = [
  {value: 'parent_vendor', name: 'Supplier', checked: true, position: 1 },
  {value: 'contract_id', name: 'Contract ID', checked: true, position: 2 },
  {value: 'contract_title', name: 'Contract Title', checked: false , position: 3},
  {value: 'contract_owner_name', name: 'Contract Owner', checked: true, position: 4},
  {value: 'wbs_element', name: 'WBS #', checked: true, position: 5},
  {value: 'ariba_doc_id', name: 'Ariba Doc ID', checked: true , position: 6},
  {value: 'jobtyp', name: 'Job Type', checked: false , position: 7},
  {value: 'npt_date_start', name: 'NPT Start', checked: false, position: 8 },
  {value: 'npt_date_end', name: 'NPT End', checked: false, position: 9 },
  {value: 'npt_duration', name: 'NPT (Hr)', checked: true, position: 10 },
  {value: 'submit_date', name: 'Submit Date', checked: false , position: 11},
  {value: 'work_start_date', name: 'Invoice Start', checked: false , position: 12},
  {value: 'work_end_date', name: 'Invoice End', checked: false , position: 13},
  {value: 'price', name: 'Invoice Total', checked: false , position: 14},
  {value: 'pt_spent_leakage_npt', name: 'Leakage Identified', checked: true, position: 15 },
  // {value: 'spent_leakage_confirmed', name: 'Leakage Confirmed', checked: true, position: 9 },
  {value: 'recovered', name: 'Leakage Recovered', checked: true, position: 16 },
  {value: 'status', name: 'Status', checked: true, position: 17 },
  {value: 'comment', name: 'Comments', checked: true, position: 18 },
  {value: 'by_date', name: 'By Date', checked: false , position: 19} ,
  { value: 'npt_ref_no', name: 'NPT#', checked: false, position: 20 },
  {value: 'is_weather', name: 'By Weather ', checked: false , position: 21},
  {value: 'modified_by', name: 'Modified By', checked: true, position: 22},
  {value: 'modified_date', name: 'Modified Date', checked: true, position: 23},
  {value: 'key', name: 'ID', checked: true , position: 24}
];
